# Tensor Manipulation

## Imports

In [19]:
import numpy as np
import torch

## Numpy Review

### 1D Array with Numpy

In [21]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [ ]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

In [4]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1]) # Element
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1])   # Slicing
print('t[:2] t[3:]     = ', t[:2], t[3:])      # Slicing

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


### 2D Array with NumPy

In [5]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [6]:
print('Rank of t : ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t :  2
Shape of t:  (4, 3)


## PyTorch is like NumPy

### 1D Arraay with PyTorch

In [7]:
t =  torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


### Notice
```t.size()``` in PyTorch is alias of ```t.shape```

Otherwise, ```t.size``` is indicating the total amount of elements in tensor in NumPy.

In [8]:
print(t.dim()) #rank
print(t.shape) #shape
print(t.size())#shape
print(t[0], t[1], t[-1]) #Element
print(t[2:5], t[4: -1]) #Slicing
print(t[:2], t[3:]) #Slicing
print(t.size(dim =0)) #size with dim


1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])
7


### 2D Array with PyTorch

In [9]:
t = torch.FloatTensor([[1., 2., 3.],
                 [4., 5., 6.],
                 [7., 8., 9.],
                 [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [10]:
print(t.dim()) #rank
print(t.size())#shape
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### Shape, Rank, Axis

In [11]:
t = torch.FloatTensor([[[[1, 2, 3, 4],
                         [5, 6, 7, 8],
                         [9, 10, 11, 12]],
                        [[13, 14, 15, 16],
                         [17, 18, 19, 20],
                         [21, 22, 23, 24]]
                        ]])

In [12]:
print(t.dim())
print(t.size())

4
torch.Size([1, 2, 3, 4])


## BroadCasting

In [13]:
#Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [14]:
#Vector + Scalar
m1 = torch.FloatTensor([1, 2])
m2 = torch.FloatTensor([3])
print(m1 + m2)

tensor([4., 5.])


In [15]:
# 1 x 2 Vector + 2 x 1 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


## Frequently Used Operations in PyTorch

### Multiplication(Elementwise Multiplication) vs MatMul(Inner Product == Dot Product)

In [16]:
print()
print('MatMul')
print()
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])

print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print()
print('multiplication')
print(m1.mul(m2)) # 2x2
print()
print('matrix multiplication')
print(m1.matmul(m2)) # 2 x 1


MatMul

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])

multiplication
tensor([[1., 2.],
        [6., 8.]])

matrix multiplication
tensor([[ 5.],
        [11.]])


### Mean

In [17]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


You can't use ```mean()``` on integers

In [18]:
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [20]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [22]:
print(t.mean())
print(t.mean(dim = 0))
print(t.mean(dim = 1))
print(t.mean(dim= -1))

3.0


TypeError: _mean() got an unexpected keyword argument 'dim'

### Sum

In [24]:
t = torch.FloatTensor([[1, 2], [3, 4], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.],
        [3., 4.]])


In [25]:
print(t.sum())
print(t.sum(dim = 0))
print(t.sum(dim = 1))
print(t.sum(dim =-1))

tensor(17.)
tensor([ 7., 10.])
tensor([3., 7., 7.])
tensor([3., 7., 7.])


### Max and Argmax

In [26]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


The ```max``` operator returns one value if it is called without an argument.

In [27]:
print(t.max()) # Returns one value: max

tensor(4.)


The ```max``` operator returns 2 values when called with dimension specified. The first valule is the maximum value, and the second value is the argmax; the index of the element with maximum value.

In [28]:
print(t.max(dim = 0)) #Returns two values: max and argmax
print('Max: ', t.max(dim=0)[0])#Max
print('Argmax: ', t.max(dim=0)[1])#Argmax

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [29]:
print(t.max(dim = 1))
print(t.max(dim = -1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


## View

In [30]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
               
               [[6, 7, 8],
               [9, 10, 11]]])

ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [31]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [32]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1 , 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## Squeeze

```tensor.squeeze(dim)``` 

removes the dimension where the size is 1 in a tensor

argument gets the dimension of tensor which to be squeezed

In [33]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [34]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


## Unsqueeze

```tensor.unsqueeze(dim)``` 

adds the dimension where the size is 1 in a tensor

argument gets the dimension of tensor which to be unsqueezed

In [35]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [36]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


We can make same effect for the dimension with ```ft.view()```

In [37]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [38]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [39]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### Scatter (for one-hot encoding)

```Tensor.scatter_(dim, index, src)```

write all elements by src in Tensor with indcies of index with the corresponding dimension

In [40]:
lt = torch.LongTensor([[0], [1], [2], [0]])
print(lt)

tensor([[0],
        [1],
        [2],
        [0]])


In [41]:
one_hot = torch.zeros(4, 3) #batch_size = 4, classes = 3
one_hot.scatter_(1, lt, 1)
print(one_hot)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])


### Casting

In [42]:
lt = torch.LongTensor([, 2, 3, 4])
print(lt)

SyntaxError: invalid syntax (<ipython-input-42-6c7e32d73b32>, line 1)

In [43]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [44]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


### Concatenation

In [45]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [46]:
print(torch.cat([x, y], dim = 0))
print(torch.cat([x, y], dim = 1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking

creating dimension of number of elements in the list at the corresponding dimension of concatinated matrix

In [74]:
x = torch.FloatTensor([1, 4])# (2,)
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [75]:
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim = 1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [62]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))
print(torch.cat([x.unsqueeze(1), y.unsqueeze(1), z.unsqueeze(1)], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


### Ones and Zeros Like

In [80]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [81]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place Operation

In [82]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [83]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


### Zip

In [86]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [87]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
