# Lab 4.2: Load Data

Edited By Steve Ive

Reference from Seungjae Lee

https://github.com/deeplearningzerotoall/PyTorch/blob/master/lab-04_2_load_data.ipynb

## Slicing 1D Array

In [77]:
nums = [0, 1, 2, 3, 4]

In [78]:
print(nums)

[0, 1, 2, 3, 4]


contain index 2 before 4

In [79]:
print(nums[2:4])

[2, 3]


bring all from index 2

In [80]:
print(nums[2:])

[2, 3, 4]


bring all before index 2

In [81]:
print(nums[:2])

[0, 1]


bring all

In [82]:
print(nums[:])

[0, 1, 2, 3, 4]


bring all before the last index

In [83]:
print(nums[:-1])

[0, 1, 2, 3]


We can assign too!

In [84]:
nums[2:4] = [8, 9]

In [85]:
print(nums)

[0, 1, 8, 9, 4]


## Slicing 2D Array

In [86]:
import numpy as np

In [87]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [88]:
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [89]:
b[:, 1]

array([ 2,  6, 10])

In [90]:
b[-1]

array([ 9, 10, 11, 12])

In [91]:
b[-1, :]

array([ 9, 10, 11, 12])

In [92]:
b[-1, ...]

array([ 9, 10, 11, 12])

In [93]:
b[0:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Loading Data from .csv file

In [94]:
import numpy as np

In [95]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)

### Take a Moment!

```y_data = xy[:, [-1]]```

brings the all rows of last column with [] array wrapped

In [96]:
x_data = xy[:, 0: -1]
y_data = xy[:, [-1]]

In [97]:
print(x_data.shape)
print(len(x_data))
print(x_data[:5])

(25, 3)
25
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]]


In [98]:
print(y_data.shape)
print(len(y_data))
print(y_data[:5])

(25, 1)
25
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]


## Imports

In [99]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [100]:
torch.manual_seed(1)

## Low-level Implementation

In [101]:
#Data
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

#Model Initialize
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

#Set optimizer
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20

for epoch in range(nb_epochs + 1):

    #Hypothesis
    pred = x_train.matmul(W) + b

    #Cost
    cost = torch.mean((pred - y_train)**2)

    #Reduce cost
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Hypotheis: {} Cost: {:.6f}'.format(epoch, nb_epochs, pred.squeeze().detach(), cost.item()))

Epoch    0/20 Hypotheis: tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.]) Cost: 26811.960938
Epoch    1/20 Hypotheis: tensor([60.3300, 72.5121, 71.4468, 77.8114, 55.3021, 40.7728, 58.2450, 43.1799,
        67.7685, 62.7711, 56.1159, 55.3320, 73.8140, 61.3605, 58.5129, 73.5830,
        58.4375, 69.8998, 70.3709, 62.9651, 68.3015, 68.0264, 65.1199, 60.8261,
        75.1500]) Cost: 9920.530273
Epoch    2/20 Hypotheis: tensor([ 97.0136, 116.6032, 114.8901, 125.1249,  88.9286,  65.5651,  93.6612,
         69.4359, 108.9755, 100.9401,  90.2373,  88.9771, 118.6964,  98.6703,
         94.0921, 118.3256,  93.9699, 112.4028, 113.1596, 101.2509, 109.8326,
        109.3903, 104.7163,  97.8108, 120.8450]) Cost: 3675.298828
Epoch    3/20 Hypotheis: tensor([119.3189, 143.4130, 141.3056, 153.8940, 109.3752,  80.6404, 115.1964,
         85.4014, 134.0320, 124.1496, 110.9851, 109.4354, 145.9869, 121.3560,
        115.7265, 145.5315, 115

## High-level Implementaion with ```nn.Module```

In [102]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)

    def forward(self, x):
        return self.linear(x)

In [103]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

model = MultivariateLinearRegressionModel()

optimizer = optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 20

for epoch in range(nb_epochs + 1):

    #Hypothesis
    pred = model(x_train)

    #cost
    cost = F.mse_loss(pred, y_train)

    #Reduce Cost
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Hypothesis: {} Cost: {:.6f}'.format(epoch, nb_epochs, pred.squeeze().detach(), cost.item()))

Epoch    0/20 Hypothesis: tensor([-6.7933, -4.8968, -6.5155, -7.3361, -2.6660, -1.8403, -6.6781, -6.7331,
        -4.0525, -3.9151, -5.2111, -3.7514, -6.4568, -4.7845, -6.2377, -5.4874,
        -3.2482, -8.9763, -6.6201, -6.2942, -7.3238, -5.0026, -7.1896, -6.2176,
        -5.5024]) Cost: 28693.490234
Epoch    1/20 Hypothesis: tensor([55.6147, 70.1117, 67.3916, 73.1548, 54.5398, 40.3360, 53.5729, 37.9342,
        66.0489, 61.0169, 52.8371, 53.4856, 69.8990, 58.6889, 54.2903, 70.6290,
        57.2013, 63.3310, 66.1742, 58.8394, 63.3299, 65.3660, 60.1730, 56.7034,
        72.2351]) Cost: 10618.750000
Epoch    2/20 Hypothesis: tensor([ 93.5619, 115.7207, 112.3309, 122.0975,  89.3237,  65.9814,  90.2090,
         65.0951, 108.6743, 100.4994,  88.1336,  88.2888, 116.3270,  97.2834,
         91.0948, 116.9119,  93.9569, 107.2983, 110.4365,  98.4438, 106.2914,
        108.1538, 101.1332,  94.9621, 119.5033]) Cost: 3936.015381
Epoch    3/20 Hypothesis: tensor([116.6357, 143.4532, 139.6562, 151

## Dataset and DataLoader